#' Hierarchical selection
#'
#' This is a function which automatically generates metabolite clusters using hierarchical clustering and find all trees of interest from each subcluster.
#'
#' @param rule A \code{rule} object containing a target clinical outcome, maximum level, and p value
#' @param sgi_params A \code{sgi_params} object containing information including the data, clinical outcomes, etc
#' @param metabolite_dist Distance metric for clustering metabolites
#' @param metabolite_linkage Linkage method for metabolite hierarchical clustering
#' @param cluster_min The minimum cluster size that should be considered for input to SGI (at least 2)
#' @param cluster_max The maximum cluster size that should be considered for input to SGI 
#' @param correction_opt The method used for multiple testing corrected, either simes or bonferroni
#' @param plot Whether to display plots of sgi trees that are of interest according to the selection rule. Since there are many subclusters, it is recommended to do this individually after getting the results from the function.
#' @param supp_plot Whether to display supplementary plots to the sgi trees -- this includes the location of the cluster in the dendrogram and a list of biomolecules if a cluster size is small
#' @param return_dend Whether to return the dendrogram generated by hierarchically clustering the dataset
#' @param output_names The output names of the AutoSGI files
#' @return Always returns a list of all metabolite clusters, as well as a boolean vector indicating if each tree generated by the subcluster is of interest based on the \code{rule} object. Optionally returns the tree with metabolite clusters as nodes.
#' @export
#' @examples
#' \dontrun{
#' }
#'
#'
hierarchical_selection <- function(rule = rule_init(), sgi_params, cluster_min = NULL, cluster_max = NULL,
                                 metabolite_dist = "euclidean", metabolite_linkage = "ward.D2", correction_opt = "simes",
                                 plot = T, supp_plot = F, summary_plot = F, return_dend = F, 
                                 output_names = list(sgi_plots = "hierarchical-selection-results.pdf", 
                                                     summary = "hierarchical-selection-summary.pdf", 
                                                     cluster_results = "hierarchical-selection-labels.xlsx", 
                                                     cluster_indices = "hierarchical-selection-cluster-indices.xlsx",
                                                     sgi_as_results = "hierarchical-selection-association-results.xlsx")) {
  
  #hierarchical selection performs a hierarchical clustering of all given metabolites in dataset
  #it then finds all clusters within the bounds specified by the user and runs SGI with each of these clusters

  if (!plot & (supp_plot | summary_plot)) stop("supp plot or summary plot can only be true if plot is true")
  if (summary_plot & !("summary" %in% names(output_names))) stop("summary plot wanted but name not specified.")
  if (correction_opt != "simes" & correction_opt != "bonferroni" & correction_opt != "extended_simes") stop("correction must be extended simes, simes, or bonferroni.")
  
  #get information from sgi_params object
  dataset = sgi_params$dataset
  clins = sgi_params$clins
  minsize = sgi_params$minsize
  user_defined_tests = sgi_params$user_defined_tests
  sgi_distance = sgi_params$sgi_distance 
  sgi_linkage = sgi_params$sgi_linkage
  
  #get information from rule object
  target_outcome = rule$target_outcome
  max_level = rule$max_level
  p_value = rule$p_value
  
  normalized_dataset <- dataset %>% t()
  hc_metabolite = hclust(as.dist(as.matrix(1 - cor(dataset))), method = metabolite_linkage) #cluster metabolite
  #hc_metabolite = hclust(dist(normalized_dataset, method = metabolite_dist), method = metabolite_linkage) #cluster metabolite
  plot(hc_metabolite)
  
  dend = as.dendrogram(hc_metabolite)
  
  #replace null bounds with least strict bound for min/max
  if (is.null(cluster_min)) {
    cluster_min = 2
  }
  if (is.null(cluster_max)) {
    cluster_max = ncol(dataset)
  }
  
  if (cluster_min < 2 | cluster_min > ncol(dataset) | cluster_max < 2 | cluster_max > ncol(dataset) | cluster_min > cluster_max) {
    stop("cluster size should be between 2 and #metabolites; cluster_max should be at least cluster_min")
  }
  
  #getting all subtrees
  #dendrapply indexing off --> just use list
  nodes = 2 * ncol(dataset) - 1
  all_subtrees = vector(mode = "list")
  valid = vector()
  suppressWarnings({dendrapply(dend, function(x) {
    l = length(labels(x))
    vt = (l >= cluster_min & l <= cluster_max)
    all_subtrees[[length(all_subtrees) + 1]] <<- labels(x)
    valid <<- c(valid, vt)
  })})
  subtrees <- all_subtrees[which(unlist(valid))] %>% unique() #should be all unique
  #print(length(subtrees))
  
  cat("Done generating subtrees\n")
  cat("-------------------------\n")
  
  if (length(subtrees) == 0) {
    stop("No subtrees within minimum and maximum range")
  }
  
  rescs = process_clusters(subtrees, rule, dataset, clins, minsize, user_defined_tests, sgi_distance, sgi_linkage, plot, correction_opt)
  
  results = rescs$results
  cluster_labels = rescs$cluster_labels
  cluster_indices = rescs$cluster_indices
  cluster_ids = rescs$cluster_ids
  sgi_plots = rescs$sgi_plots
  asx = rescs$asx
  
  if (plot) {
    
    #calc dend labels
    colors <- vector(length = nodes)
    ridx = 1
    didx = 1
    
    dendrapply(dend, function(x) {
      if (didx > length(valid) | !valid[didx]) {
        colors[didx] <<- "unprocessed"
      }
      else {
        if (results[ridx]) {
          colors[didx] <<- "good"
        }
        else {
          colors[didx] <<- "bad"
        }
        ridx <<- ridx + 1
      }
      didx <<- didx + 1
    })
    
    ggd <- ggdendro::dendro_data(hc_metabolite, type = "rectangle") #get ggdendro representation
    xy <- get_nodes_xy(dend, type = "rectangle") #get x, y coordinates
    
    if (summary_plot) {
      
      scale = ncol(dataset)/1200 #everything linearly scales except height
      hscale = log2(ncol(dataset + 1))/log2(1200)
      
      pdf(output_names$summary, width = 220 * scale, height = 85 * hscale)
      
      dend_sizes = rep(25 * scale, times = nnodes(dend)) #adjust node sizes too
      dend_adjust = rep(1, times = nnodes(dend))
      adji = 1
      
      dendrapply(dend, function(x) {
        if (adji > length(valid) | !valid[adji]) {
          const = 0.25
          dend_adjust[adji] <<- const * min(1.6, log2((length(all_subtrees[[adji]])/cluster_min) + 1))
        }
        adji <<- adji + 1
      })
      
      dend_sizes = dend_sizes * dend_adjust
      
      legend_sz = 150 * scale
      mg_sz = 500 * scale
      
      #green denotes interesting cluster, red not interesting
      #grey means not processed
      
      plot(ggdendrogram(ggd) + 
             geom_point(aes(x = xy[, 1], y = xy[, 2], colour = colors), size = dend_sizes) + 
             scale_color_manual(values = c("good" = "#3c824e", "bad" = "red", "unprocessed" = "grey")) + 
             theme_dendro() + 
             guides(shape = guide_legend(override.aes = list(size = legend_sz))) + 
             guides(color = guide_legend(override.aes = list(size = legend_sz))) +
             theme(legend.title = element_text(size = legend_sz), 
                   legend.text = element_text(size = legend_sz), 
                   legend.margin = margin(mg_sz, mg_sz, mg_sz, mg_sz)))
      
      dev.off()
      
    }
    
    pdf(output_names$sgi_plots, onefile = TRUE)
    
    par(mar = c(0,0,0,0))
    
    summary = "Tree-Based Selection Plots\n------------------------------------\n"
    num_interest = sum(results) #number of trees satisfying rule
    summary = paste0(summary, num_interest, " trees of interest, out of ", length(subtrees), " clusters\n")
    summary = paste0(summary, "Rule used: ", capture.output(print.rule(rule)), "\n")
    
    plot.new()
    
    text(x = 0.5, y = 0.5, paste(summary), 
         cex = 0.9, col = "black")
    
    par(oma=c(0, 0, 0, 0))
    par(mar=c(1.1, 1.1, 1.1, 1.1))
    
    cluster = 1
    valid_cid = which(colors == "good")
    orig_tree = ggdendrogram(ggd)
    
    sapply(seq(length(sgi_plots)), function(i) {
      plot(sgi_plots[[i]])
      title(main = paste0("Cluster ", cluster_ids[i]), cex.main = 0.9, line = -0.5) #make sure to use cluster_id (skipping over non-valid trees)
      if (!supp_plot) {
        return()
      }
      #supp_plots below...
      #add tree summary + cluster_ids (if visible)
      #tree summary is location of cluster in dendrogram
      #cluster_ids is metabolites if its a small subset (might be interesting to see subgroup)
      vcid = valid_cid[i]
      tree_point = orig_tree + geom_point(aes(x = xy[, 1][vcid], y = xy[, 2][vcid]), colour = "green") +
        geom_label_repel(aes(x = xy[, 1][vcid], y = xy[, 2][vcid], 
                             label = paste0("Cluster ", cluster_ids[i])),
                         colour = "#3c824e", 
                         position = position_nudge_repel(x = ifelse(xy[, 1][vcid] - 50 < 0, 50, -50), 
                                                         y = ifelse(xy[, 2][vcid] - 50 < 0, 50, -50)), 
                         arrow = arrow(length = unit(0.015, "npc"))) +
        theme_dendro()
      
      display_features(all_subtrees[[vcid]], tree_point, maximum = 10)
    })
    
    dev.off()
    
    #also return an excel file
    #this is the labels for each subtree generated from clustering
    cluster_data <- data.frame(clusters = seq(length(subtrees)), labels = cluster_labels)
    cluster_indices <- data.frame(cluster_indices)
    
    indices_colnames <- sapply(seq(length(subtrees)), function(i){
      return(paste0("CLST", i))
    })
    
    colnames(cluster_indices) <- indices_colnames
    
    write_xlsx(cluster_data, path = output_names$cluster_results)
    write_xlsx(cluster_indices, path = output_names$cluster_indices)
    
    #now all the data needed to reconstruct as object
    as_sheet = combined_as_sheet(asx)
    names(as_sheet) = do.call("c", lapply(seq(length(asx)), function(i){paste0("SGI ", i)}))
    write_xlsx((as_sheet), path = output_names$sgi_as_results)
    
  }
  
  if (return_dend) {
    #return subtrees, results, and the dendrogram
    return(list(subtrees = subtrees, results = results, dend = dend))
  }
  
  return(list(subtrees = subtrees, results = results))
  
}
